resources:
  - name: demo_node_app_git
    type: GitRepo
    configuration:
      gitProvider: rkfrog
      path: rkfrog/demo-node-app
      branches:
        include: main
      buildOn:
        commit: true
        pullRequestCreate: true
  - name: demo_node_app_dev_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: rk_jf_rt_saas
      buildName: demo_node_app_jf_ci
      buildNumber: 1
  - name: demo_node_app_qa_promoted_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: rk_jf_rt_saas
      buildName: demo_node_app_jf_ci
      buildNumber: 1

#pipeline code
pipelines:
  - name: demo_node_app_jf_ci
    steps:
      - name: npm_build
        type: NpmBuild
        configuration:
          repositoryName: demonode-npm-dev-virtual
          sourceLocation: ./
          integrations:
              - name: rk_jf_rt_saas
          inputResources:
            - name: demo_node_app_git
      - name: npm_publish
        type: NpmPublish
        configuration:
          repositoryName: demonode-npm-dev-virtual
          autoPublishBuildInfo: true
          integrations:
            - name: rk_jf_rt_saas
          inputSteps: 
            - name: npm_build
          outputResources:
            - name: demo_node_app_dev_buildinfo
      - name: xray_scan
        type: XrayScan
        configuration:
          inputResources:
            - name: demo_node_app_dev_buildinfo
      - name: demo_node_app_build_promote_QA
        type: PromoteBuild
        configuration:
          targetRepository: demonode-npm-test-local
          includeDependencies: true
          status: "QA-Tested"
          comment: "This build has passed all QA testing > $run_number"
          copy: true
          inputResources:
            - name: demo_node_app_dev_buildinfo
          outputResources:
            - name: demo_node_app_qa_promoted_buildinfo