resources:
  - name: demo_node_app_git
    type: GitRepo
    configuration:
      gitProvider: rkfrog
      path: rkfrog/demo-node-app
      branches:
        include: main
      buildOn:
        commit: true
        pullRequestCreate: true

#pipeline code
pipelines:
  - name: demo_node_app_ci
    steps:
      - name: npm_build
        type: NpmBuild
        configuration:
          repositoryName: demonode-npm-dev-virtual
          sourceLocation: ./
          integrations:
              - name: rk_jf_rt_saas
          inputResources:
            - name: demo_node_app_git