name: demo-node-app-docker-build

on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:

jobs:
  push-to-repo:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "The job was triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          echo "${{ github.repository }} repository has been cloned to the runner."
      - name: Show current directory
        run: |
          pwd
      - name: List files in the repository
        run: |
          ls -ltrh ${{ github.workspace }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: "18.5.0"
          registry-url: 'https://roskad.jfrog.io/artifactory/api/npm/demonode-npm-dev-virtual/'
          always-auth: true
          email: 'roshank@jfrog.com'
      # - name: Authenticate with private NPM package
      #   run: |
      #     printenv
      #     echo "@<SCOPE>:registry=https://$REPO_URL/
      #     //$REPO_URL/:_password=${{ secrets.NODE_AUTH_TOKEN }}
      #     //$REPO_URL/:username=$USERNAME
      #     //$REPO_URL/:email=$USERNAME
      #     //$REPO_URL/:always-auth=true" > ~/.npmrc
      #   env:
      #     REPO_URL: ${{ env.RK_JRT_NPM_VIRTUAL_REPO_URL }}
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_RK_JRT_NPM_VIRTUAL_TOKEN }}
      #     USERNAME: ${{ env.RK_JRT_REPO_USERNAME }}
      - name: List npm config
        run: npm config ls -l
      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_RK_JRT_NPM_VIRTUAL_TOKEN }}
      # - name: Run test
      #   run: npm test
      - name: Bump version
        run: npm run minor
      - name: Publish
        run: npm publish --dry-run