name: demo-node-app-docker-build
on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:
jobs:
  push-to-repo:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "The job was triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          echo "${{ github.repository }} repository has been cloned to the runner."
      - name: Show current directory
        run: |
          pwd
      - name: List files in the repository
        run: |
          ls -ltrh ${{ github.workspace }}
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "18.5.0"
      - name: List npm config
        run: npm config ls -l
      - name: Install dependencies
        run: npm install
      # - name: Run test
      #   run: npm test
      - name: Bump version
        run: npm run minor
      - name: Publish
        run: npm publish --dry-run